### ISSUE TITLE
Blog pages

### ISSUE THREAD

**Issue by andreimarin90** [andreimarin90/Showoff_HTML#1]
tu ai pus artiolele pe coloane, nu pe rand. astfel, daca avem coloane cu 3 posturi, postul nr 4 de pe pagina este in pozitia dreapta sus. Ar trebui acolo sa fie postul nr 2. am nevoie de ele in ordinea asta ca sa le pot display newest first
si trebuie facut probabil cu isotope
sau cu float left si 49.9%
si sa nu mai avem: <div class="column-right"><div class="column-left">

**Comment by arlad** [comment]
Fixed.
