### ISSUE TITLE
Column split

### ISSUE THREAD

**Issue by andreimarin90** [andreimarin90/Showoff_HTML#12]
atunci cand se intampla sa fie sectiuni ca de exemplu pe about-me page, sectiunea cu My Mission, my My Philosophy, e bine sa putem face acolo layoutul din coloane. momentan nu e posibil. so in loc sa avem md-10 offset-1 ca acu, sa avem 3 coloane (md 3 sau md4 sau cum vine acolo). 

De asemenea daca mai exista astfel de sectiuni care sa nu fie parte dintr'un shortcode "dintr-o bucata" ar fi bine sa adaptam tot asa. De ex acest sc s'ar face pe 3 coloane, fiecare cu titlu si text. Cel de sub cu acele numere e bine asa cum e, acolo nu e nevoie, sau de exemplu pe unde ai facut cu <li> pe index cu acele services. Deocamdata cred ca decat aici am intalnit, asa ca hai sa modificam aici for now si daca mai e ceva te mai anunt eu.

Cheers

**Comment by arlad** [comment]
Done.
