### ISSUE TITLE
Services Index (style3)

### ISSUE THREAD

**Issue by andreimarin90** [andreimarin90/Showoff_HTML#16]
As vrea pe astea sa le facem in <div>, nu ul>li. si as vrea sa fie facute astfel incat un shortcode sa reprezinte un rand din acela. Adica sa intre si clasele necesare de pe la <ul class="services style3"> sub acest div, pentru fiecare din sectiuni.

Ceva mai mult markup dar mai multa versatilitate pentru WP.

**Comment by arlad** [comment]
Done.
