### ISSUE TITLE
Menu socials

### ISSUE THREAD

**Issue by andreimarin90** [andreimarin90/Showoff_HTML#21]
te rog sa scoti socialele din ul la meniu. Face lucrurile tare complicate in back-end.

Cheers

**Comment by arlad** [comment]
Done.

**Comment by andreimarin90** [comment]
Nu ne'am inteles bine aici :D. Scuze, eu sunt de vina ca nu am scris cum trebuie comentul. Scoate socialele din "ul" tag, lasa'le in div separat de ul menu.

**Comment by arlad** [comment]
Done.
