### ISSUE TITLE
Services-1.php

### ISSUE THREAD

**Issue by andreimarin90** [andreimarin90/Showoff_HTML#25]
Separa te rog sectiunea cu fata aceea de acel titlu. lasa titlu in section singur, si apoi fata aia singura in section. 

Te rog asta, pentru ca in Visual C. nu poti face prea multi children row-> cols -> row -> cols. De aceea e bine sa bagam direct row cu fata aia in sectiune, in loc sa fie sub col-sm-10 offset-1 acela. Sa fie acele sm-5 sm-7 direct in row (redeclarate diferit ca sa pastreze stilizarea ofc)

**Comment by arlad** [comment]
Done.
