### ISSUE TITLE
Footer Widgets ul vs div

### ISSUE THREAD

**Issue by andreimarin90** [andreimarin90/Showoff_HTML#4]
Scuze ca te ametesc, dar tot mai bine era cu 2 ul's cum era initial. Revert schimbarile pe care le'ai facut aici pls: https://github.com/andreimarin90/Showoff_HTML/commit/3dec8b56f0e5e63c862cd61b2e156c9c2bfa871f

10x

**Comment by arlad** [comment]
Fixed.
