### ISSUE TITLE
Slider z-index

### ISSUE THREAD

**Issue by andreimarin90** [andreimarin90/Showoff_HTML#9]
![screen shot 2015-12-03 at 17 31 08](https://cloud.githubusercontent.com/assets/8208159/11564802/ad62081a-99e3-11e5-83ea-6c5c3e56ca11.jpg)

**Comment by arlad** [comment]
Aici n-avem nici o sansa, pentru ca title e in slide, da sageata e in tot slider. Sau sageata in top de slide, sau slide in top de sageata cu tot cu title si imaginea, deci in acest caz sageata va fi invisible.

**Comment by andreimarin90** [comment]
Ok, no problem.
